# Generated by Django 5.0.6 on 2024-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='created_at',
        ),
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='annonces/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('canceled', 'Annulée')], default='pending', max_length=10),
        ),
    ]
