# Generated by Django 5.0.6 on 2024-09-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_annonce_created_at_remove_annonce_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, default='/default/image.png', null=True, upload_to='annonces/'),
        ),
    ]
